//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grasshoppers {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Grasshoppers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string InventoryQuery_Name {
            get {
                return ResourceManager.GetString("InventoryQuery_Name", resourceCulture);
            }
        }
        
        public static string MostFreqPlayedMissionQuery_Name {
            get {
                return ResourceManager.GetString("MostFreqPlayedMissionQuery_Name", resourceCulture);
            }
        }
        
        public static string GameSessionMvpQuery_Name {
            get {
                return ResourceManager.GetString("GameSessionMvpQuery_Name", resourceCulture);
            }
        }
        
        public static string CharsOwnItemQuery_Name {
            get {
                return ResourceManager.GetString("CharsOwnItemQuery_Name", resourceCulture);
            }
        }
        
        public static string SexOrientedGameSessionQuery_Name {
            get {
                return ResourceManager.GetString("SexOrientedGameSessionQuery_Name", resourceCulture);
            }
        }
        
        public static string CaptureMasterQuery_Name {
            get {
                return ResourceManager.GetString("CaptureMasterQuery_Name", resourceCulture);
            }
        }
        
        public static string FastestWinTeamQuery_Name {
            get {
                return ResourceManager.GetString("FastestWinTeamQuery_Name", resourceCulture);
            }
        }
        
        public static string StunMasterQuery_Name {
            get {
                return ResourceManager.GetString("StunMasterQuery_Name", resourceCulture);
            }
        }
    }
}
