//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grasshoppers {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Grasshoppers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string InventoryGrasshoppersQuery_Name {
            get {
                return ResourceManager.GetString("InventoryGrasshoppersQuery_Name", resourceCulture);
            }
        }
        
        public static string MostFreqPlayedMissionGrasshoppersQueryIGrasshoppersQuery_Name {
            get {
                return ResourceManager.GetString("MostFreqPlayedMissionGrasshoppersQueryIGrasshoppersQuery_Name", resourceCulture);
            }
        }
        
        public static string GameSessionMvpGrasshoppersQuery_Name {
            get {
                return ResourceManager.GetString("GameSessionMvpGrasshoppersQuery_Name", resourceCulture);
            }
        }
        
        public static string CharsOwnItemGrasshoppersQuery_Name {
            get {
                return ResourceManager.GetString("CharsOwnItemGrasshoppersQuery_Name", resourceCulture);
            }
        }
        
        public static string SexOrientedGameSessionGrasshoppersQuery_Name {
            get {
                return ResourceManager.GetString("SexOrientedGameSessionGrasshoppersQuery_Name", resourceCulture);
            }
        }
        
        public static string CaptureMasterGrasshoppersQuery_Name {
            get {
                return ResourceManager.GetString("CaptureMasterGrasshoppersQuery_Name", resourceCulture);
            }
        }
        
        public static string FastestWinTeamGrasshoppersQuery_Name {
            get {
                return ResourceManager.GetString("FastestWinTeamGrasshoppersQuery_Name", resourceCulture);
            }
        }
        
        public static string StunMasterGrasshoppersQuery_Name {
            get {
                return ResourceManager.GetString("StunMasterGrasshoppersQuery_Name", resourceCulture);
            }
        }
    }
}
